"""Turn an :class:`~model.InstallConfig` into an ordered, inspectable plan.

A plan is a plain list of :class:`Step` objects. Nothing here runs commands or
touches a disk — :mod:`engine` does that. Because planning is a pure function
of (config, disk), the exact partitioning, mkfs, copy, fstab and bootloader
steps are asserted directly in the unit tests (§14 non-negotiables as code).
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Callable

from .model import (
    ALIGN_MIB,
    BOOT_MIB,
    FIRST_128_GIB_MIB,
    InstallConfig,
    Partition,
    partition_path,
)

# Directories never copied from the live root onto the target.
COPY_EXCLUDES = (
    "/dev/*", "/proc/*", "/sys/*", "/run/*", "/tmp/*", "/mnt/*", "/media/*",
    "/lost+found", "/target", "/target/*", "/swapfile",
    "/var/cache/apt/archives/*.deb", "/live", "/run/live",
)


@dataclass
class Step:
    """A single install action.

    Exactly one of *argv* / *write* is set. *argv* is a command to run;
    *write* is a ``(path, render)`` pair where ``render(ctx)`` returns the
    file's text (computed at execute time so it can use probed UUIDs).
    """

    title: str
    argv: list[str] | None = None
    destructive: bool = False
    chroot: bool = False
    write: tuple[str, Callable[[dict], str]] | None = None
    sensitive: bool = False  # redact args when logging (passwords)
    stdin_key: str | None = None  # feed a secret (by key) to this step's stdin

    def describe(self) -> str:
        if self.write is not None:
            return f"write {self.write[0]}"
        assert self.argv is not None
        shown = "<redacted>" if self.sensitive else " ".join(self.argv)
        prefix = "[in target] " if self.chroot else ""
        return prefix + shown


@dataclass
class Plan:
    config: InstallConfig
    partitions: list[Partition]
    steps: list[Step] = field(default_factory=list)

    @property
    def boot(self) -> Partition:
        return next(p for p in self.partitions if p.role == "boot")

    @property
    def swap(self) -> Partition:
        return next(p for p in self.partitions if p.role == "swap")

    @property
    def root(self) -> Partition:
        return next(p for p in self.partitions if p.role == "root")


def build_layout(cfg: InstallConfig, disk_size_mib: int) -> list[Partition]:
    """Guided whole-disk layout: /boot, swap, / (msdos, old-BIOS safe)."""
    swap_mib = cfg.resolved_swap_mib()
    start = ALIGN_MIB
    boot_end = start + BOOT_MIB
    # /boot must live inside the first 128 GiB (§6.2).
    assert boot_end <= FIRST_128_GIB_MIB
    swap_end = boot_end + swap_mib
    parts = [
        Partition(1, "boot", start, boot_end, "ext4", "castalia-boot"),
        Partition(2, "swap", boot_end, swap_end, "swap", "castalia-swap"),
        Partition(3, "root", swap_end, disk_size_mib, "ext4", "castalia-root"),
    ]
    return parts


def render_fstab(ctx: dict) -> str:
    """Produce /etc/fstab from probed UUIDs (ctx['uuids'][role])."""
    u = ctx["uuids"]
    lines = [
        "# /etc/fstab — generated by the Castalia installer",
        "# <file system>  <mount>  <type>  <options>  <dump>  <pass>",
        f"UUID={u['root']}  /      ext4  errors=remount-ro  0  1",
        f"UUID={u['boot']}  /boot  ext4  defaults           0  2",
        f"UUID={u['swap']}  none   swap  sw                 0  0",
    ]
    return "\n".join(lines) + "\n"


def render_hostname(ctx: dict) -> str:
    return ctx["config"].hostname + "\n"


def render_hosts(ctx: dict) -> str:
    host = ctx["config"].hostname
    return (
        "127.0.0.1\tlocalhost\n"
        f"127.0.1.1\t{host}\n"
        "::1\tlocalhost ip6-localhost ip6-loopback\n"
    )


def build_plan(
    cfg: InstallConfig,
    disk_size_mib: int,
    *,
    configure_target: bool = True,
    set_password: bool = False,
) -> Plan:
    """Full guided install plan for *cfg* against a disk of *disk_size_mib*.

    ``configure_target=False`` stops after the copy + identity files, omitting
    the chroot phase (bootloader, timezone, user). That subset needs only a
    real block device — not a bootable rootfs — so the loopback smoke can
    exercise the genuine destructive path (partition/format/mount/copy/fstab)
    against a disk image on any machine.
    """
    parts = build_layout(cfg, disk_size_mib)
    plan = Plan(cfg, parts)
    disk = cfg.target_disk
    mnt = cfg.mount_root
    boot = plan.boot
    swap = plan.swap
    root = plan.root
    bpart = partition_path(disk, boot.index)
    spart = partition_path(disk, swap.index)
    rpart = partition_path(disk, root.index)

    s = plan.steps.append

    # 1. Partition table + partitions (DESTRUCTIVE — gated in the engine).
    s(Step(f"Create MS-DOS partition table on {disk}",
           ["parted", "-s", disk, "mklabel", "msdos"], destructive=True))
    s(Step("Create /boot partition",
           ["parted", "-s", disk, "mkpart", "primary", "ext4",
            f"{boot.start_mib}MiB", f"{boot.end_mib}MiB"], destructive=True))
    s(Step("Mark /boot bootable",
           ["parted", "-s", disk, "set", "1", "boot", "on"], destructive=True))
    s(Step("Create swap partition",
           ["parted", "-s", disk, "mkpart", "primary", "linux-swap",
            f"{swap.start_mib}MiB", f"{swap.end_mib}MiB"], destructive=True))
    s(Step("Create root partition",
           ["parted", "-s", disk, "mkpart", "primary", "ext4",
            f"{root.start_mib}MiB", "100%"], destructive=True))
    s(Step("Re-read the partition table",
           ["partprobe", disk], destructive=True))

    # 2. Filesystems.
    s(Step("Format /boot (ext4)",
           ["mkfs.ext4", "-F", "-L", boot.label, bpart], destructive=True))
    s(Step("Initialise swap",
           ["mkswap", "-L", swap.label, spart], destructive=True))
    s(Step("Format root (ext4)",
           ["mkfs.ext4", "-F", "-L", root.label, rpart], destructive=True))

    # 3. Mount the target and activate swap.
    s(Step("Mount root", ["mount", rpart, mnt]))
    s(Step("Create /boot mount point", ["mkdir", "-p", f"{mnt}/boot"]))
    s(Step("Mount /boot", ["mount", bpart, f"{mnt}/boot"]))
    s(Step("Enable swap", ["swapon", spart]))

    # 4. Copy the live system onto the target.
    rsync = ["rsync", "-aHAXS", "--numeric-ids"]
    for ex in COPY_EXCLUDES:
        rsync += ["--exclude", ex]
    rsync += [f"{cfg.source_root}/", f"{mnt}/"]
    s(Step("Copy the system to disk", rsync))

    # 5. System identity files.
    s(Step("Write /etc/fstab", write=(f"{mnt}/etc/fstab", render_fstab)))
    s(Step("Write /etc/hostname",
           write=(f"{mnt}/etc/hostname", render_hostname)))
    s(Step("Write /etc/hosts", write=(f"{mnt}/etc/hosts", render_hosts)))

    # 6. Bind mounts for chroot, then bootloader + user in the chroot.
    if configure_target:
        for d in ("dev", "dev/pts", "proc", "sys"):
            src = "/" + d
            s(Step(f"Bind-mount /{d}",
                   ["mount", "--rbind", src, f"{mnt}/{d}"]))
        s(Step("Install GRUB to the disk",
               ["grub-install", "--target=i386-pc", "--recheck", disk],
               destructive=True, chroot=True))
        s(Step("Generate GRUB config",
               ["grub-mkconfig", "-o", "/boot/grub/grub.cfg"], chroot=True))
        # Make the installed system boot by root FS UUID, not the install-time
        # device path: grub-mkconfig can bake in the current device name (e.g.
        # the loopback /dev/loopNp3, or /dev/sda3 that may re-order), which then
        # fails to boot as a different device. Rewrite any root=/dev/… to
        # root=UUID=… using the UUID of whatever is mounted at / in the target.
        s(Step("Make GRUB boot by UUID (device-independent)",
               ["sh", "-c",
                'u=$(blkid -s UUID -o value "$(findmnt -no SOURCE /)"); '
                '[ -n "$u" ] && sed -i '
                '"s@root=/dev/[A-Za-z0-9]*@root=UUID=$u@g" '
                '/boot/grub/grub.cfg || true'],
               chroot=True))
        s(Step("Set the timezone",
               ["ln", "-sf", f"/usr/share/zoneinfo/{cfg.timezone}",
                "/etc/localtime"], chroot=True))
        s(Step(f"Create user {cfg.username}",
               ["useradd", "-m", "-s", "/bin/bash", "-c", cfg.full_name,
                cfg.username], chroot=True))
        s(Step("Add user to sudo/audio/video groups",
               ["usermod", "-aG", "sudo,audio,video,netdev,plugdev",
                cfg.username], chroot=True))
        # Set the password INSIDE the chroot, while /target is still mounted
        # (fed on stdin so it never touches argv/logs). Must precede unmount.
        if set_password:
            s(Step(f"Set the password for {cfg.username}",
                   ["chpasswd"], chroot=True, sensitive=True,
                   stdin_key="password"))

    # 7. Unmount everything (leave the disk clean & bootable).
    s(Step("Deactivate swap", ["swapoff", spart]))
    unmounts = ("sys", "proc", "dev/pts", "dev", "boot", "") if configure_target \
        else ("boot", "")
    for d in unmounts:
        target = f"{mnt}/{d}".rstrip("/")
        s(Step(f"Unmount {target}", ["umount", "-lf", target]))

    return plan
