// libcastalia-ui — shared theme application (Bible §6.16, §12.3).
// One helper every first-party app uses to wear the active theme: it loads
// the theme.conf tokens and the QSS generated by tools/theme_export.py, and
// applies them to the QApplication. "One switch changes everything."
#pragma once

#include <QIcon>
#include <QString>

#include "ThemeTokens.h"

class QApplication;

namespace castalia {

// Absolute path to a theme's generated QSS within a repo/asset tree.
QString themeQssPath(const QString &repoRoot, const QString &themeId);

// Absolute path to a theme's token bundle.
QString themeConfPath(const QString &repoRoot, const QString &themeId);

// Load <themeId> from repoRoot, apply its QSS (+ optional extraQss) to the
// application, and return the parsed tokens. Invalid tokens are returned
// as-is (caller checks isValid()).
ThemeTokens applyTheme(QApplication *app, const QString &repoRoot,
                       const QString &themeId,
                       const QString &extraQss = QString());

// The theme ids shipped under repoRoot/themes/*/theme.conf, in display order.
QStringList availableThemes(const QString &repoRoot);

// The session's active theme id, resolved the same way castalia-session does
// (§6.6): ~/.config/castalia/theme.conf, then /etc/castalia/theme.conf, then
// `fallback`. Lets menu/desktop launchers honour a theme changed in the
// Control Center without waiting for the next login.
QString activeThemeId(const QString &fallback = QStringLiteral("classic"));

// True when interface animations must be skipped: the user asked for it
// (CASTALIA_REDUCE_MOTION=1) or the render is head-less/deterministic
// (QT_QPA_PLATFORM=offscreen, the CI screenshot path). Animations in the
// shell are always ≤200 ms, leave no timer running afterwards, and honour
// this switch (§8.6, §16 FLOOR budgets).
bool reduceMotion();

// True when this is a live session — booted from the ISO rather than
// installed. The live launcher exports CASTALIA_LIVE=1; live-boot's own
// mountpoint is the second opinion, so the answer stays right for a session
// started some other way. What hangs on it: the desktop's "Instalar Castalia
// OS" icon, which must never appear on an installed system (§14.5).
bool isLiveSession();

// An icon from the shared 48 px family (themes/icons/48/<name>.svg).
// Returns a null icon if the asset does not exist.
QIcon themeIcon(const QString &repoRoot, const QString &name);

} // namespace castalia
